project_id = "maysttckdfnnzvfeujaj"

[functions.admin-user-management]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.check-ip-block]
verify_jwt = false

[functions.manage-ip-block]
verify_jwt = false

[functions.admin-totp]
verify_jwt = false

[functions.user-totp]
verify_jwt = false