import { useEffect } from "react";
import { useLocation } from "react-router-dom";

const S = " | Freelan Space";

const TITLES: Record<string, string> = {
  "/": "Freelance Jobs in India — Hire Top Freelancers" + S,
  "/landing": "Freelance Services in India" + S,
  "/login": "Login to Your Account" + S,
  "/forgot-password": "Forgot Password" + S,
  "/reset-password": "Reset Your Password" + S,
  "/register/employee": "Register as Freelancer" + S,
  "/register/freelancer": "Register as Freelancer" + S,
  "/register/employer": "Register as Employer" + S,
  "/register/client": "Register as Employer" + S,
  "/verification-pending": "Verify Your Account" + S,
  "/install": "Install the Freelan Space App" + S,
  "/complete-profile": "Complete Your Profile" + S,
  "/categories": "Browse Freelance Categories in India" + S,
  "/projects": "Find Freelance Projects in India" + S,
  "/pricing": "Pricing Plans" + S,
  "/how-it-works": "How Freelan Space Works" + S,
  "/community": "Freelancer Community India" + S,
  "/about": "About Us" + S,
  "/blog": "Blog — Freelancing Tips & Insights" + S,
  "/careers": "Careers at Freelan Space" + S,
  "/contact": "Contact Us" + S,
  "/unsubscribe": "Unsubscribe from Emails" + S,
  "/legal": "Legal Documents" + S,

  "/employee/dashboard": "Freelancer Dashboard" + S,
  "/employee/attendance": "Attendance Tracker" + S,
  "/employee/projects": "Browse Projects" + S,
  "/employee/requests": "My Proposals" + S,
  "/employee/bids": "My Bids" + S,
  "/employee/earnings": "My Earnings" + S,
  "/employee/reviews": "Client Reviews" + S,
  "/employee/badges": "Skill Badges" + S,
  "/employee/portfolio": "My Portfolio" + S,
  "/employee/wallet/add-money-setup": "Add Money Setup" + S,
  "/employee/wallet/add": "Add Money to Wallet" + S,
  "/employee/wallet/transactions": "Transaction History" + S,
  "/employee/wallet/activity": "Wallet Activity" + S,
  "/employee/wallet/withdrawals": "Withdrawal History" + S,
  "/employee/wallet/withdraw": "Request Withdrawal" + S,
  "/employee/wallet/qr": "My QR Code" + S,
  "/employee/wallet/my-qr": "My QR Code" + S,
  "/employee/wallet/scan": "Scan & Pay" + S,
  "/employee/wallet/deposit": "Deposit Payment" + S,
  "/employee/wallet/upgrade-chat": "Upgrade Chat" + S,
  "/employee/wallet": "My Wallet" + S,
  "/employee/my-qr": "My QR Code" + S,
  "/employee/scan-qr": "Scan & Pay" + S,
  "/employee/profile/personal": "Personal Information" + S,
  "/employee/profile/change-email": "Change Email" + S,
  "/employee/profile/mobile-verify/schedule": "Schedule Mobile Verification" + S,
  "/employee/profile/mobile-verify": "Verify Mobile Number" + S,
  "/employee/profile/professional": "Professional Details" + S,
  "/employee/profile/bank-details": "Bank Details" + S,
  "/employee/profile/work-experience": "Work Experience" + S,
  "/employee/profile/services": "My Services" + S,
  "/employee/profile/emergency-contacts": "Emergency Contacts" + S,
  "/employee/profile/aadhaar-verification": "Aadhaar Verification" + S,
  "/employee/profile/bank-verification": "Bank Verification" + S,
  "/employee/profile/upi-apps": "UPI Apps & KYC" + S,
  "/employee/profile": "My Profile" + S,
  "/employee/settings/security/mpin": "MPIN Settings" + S,
  "/employee/settings/security/google-authenticator": "Two-Factor Authentication" + S,
  "/employee/settings/security/withdrawal-password": "Withdrawal Password" + S,
  "/employee/settings/security/security-questions": "Security Questions" + S,
  "/employee/settings": "Account Settings" + S,
  "/employee/notification-settings": "Notification Preferences" + S,
  "/employee/notifications": "Notifications" + S,
  "/employee/get-free": "Get Free Coins" + S,
  "/employee/get-coins": "Earn More Coins" + S,
  "/employee/help-support": "Help & Support" + S,
  "/employee/review": "Leave a Review" + S,
  "/employee/wallet-types": "Wallet Types" + S,
  "/employee/app": "Get the Mobile App" + S,
  "/employee/projects/chat": "Project Chat" + S,
  "/employee/projects/support-chat": "Support Chat" + S,

  "/freelancer/dashboard": "Freelancer Dashboard" + S,
  "/freelancer/attendance": "Attendance Tracker" + S,
  "/freelancer/projects": "Browse Projects" + S,
  "/freelancer/requests": "My Proposals" + S,
  "/freelancer/bids": "My Bids" + S,
  "/freelancer/earnings": "My Earnings" + S,
  "/freelancer/reviews": "Client Reviews" + S,
  "/freelancer/badges": "Skill Badges" + S,
  "/freelancer/portfolio": "My Portfolio" + S,
  "/freelancer/wallet/add-money-setup": "Add Money Setup" + S,
  "/freelancer/wallet/add": "Add Money to Wallet" + S,
  "/freelancer/wallet/transactions": "Transaction History" + S,
  "/freelancer/wallet/activity": "Wallet Activity" + S,
  "/freelancer/wallet/withdrawals": "Withdrawal History" + S,
  "/freelancer/wallet/withdraw": "Request Withdrawal" + S,
  "/freelancer/wallet/qr": "My QR Code" + S,
  "/freelancer/wallet/my-qr": "My QR Code" + S,
  "/freelancer/wallet/scan": "Scan & Pay" + S,
  "/freelancer/wallet/deposit": "Deposit Payment" + S,
  "/freelancer/wallet": "My Wallet" + S,
  "/freelancer/my-qr": "My QR Code" + S,
  "/freelancer/scan-qr": "Scan & Pay" + S,
  "/freelancer/profile/personal": "Personal Information" + S,
  "/freelancer/profile/change-email": "Change Email" + S,
  "/freelancer/profile/mobile-verify": "Verify Mobile Number" + S,
  "/freelancer/profile/professional": "Professional Details" + S,
  "/freelancer/profile/bank-details": "Bank Details" + S,
  "/freelancer/profile/work-experience": "Work Experience" + S,
  "/freelancer/profile/services": "My Services" + S,
  "/freelancer/profile/emergency-contacts": "Emergency Contacts" + S,
  "/freelancer/profile/aadhaar-verification": "Aadhaar Verification" + S,
  "/freelancer/profile/bank-verification": "Bank Verification" + S,
  "/freelancer/profile/upi-apps": "UPI Apps & KYC" + S,
  "/freelancer/profile": "My Profile" + S,
  "/freelancer/settings/security/mpin": "MPIN Settings" + S,
  "/freelancer/settings/security/google-authenticator": "Two-Factor Authentication" + S,
  "/freelancer/settings/security/withdrawal-password": "Withdrawal Password" + S,
  "/freelancer/settings/security/security-questions": "Security Questions" + S,
  "/freelancer/settings": "Account Settings" + S,
  "/freelancer/notification-settings": "Notification Preferences" + S,
  "/freelancer/notifications": "Notifications" + S,
  "/freelancer/get-free": "Get Free Coins" + S,
  "/freelancer/get-coins": "Earn More Coins" + S,
  "/freelancer/help-support": "Help & Support" + S,
  "/freelancer/wallet-types": "Wallet Types" + S,
  "/freelancer/app": "Get the Mobile App" + S,

  "/employer/dashboard": "Employer Dashboard" + S,
  "/employer/projects/chat": "Project Chat" + S,
  "/employer/projects": "My Projects" + S,
  "/employer/post-job": "Post a New Job" + S,
  "/employer/wallet/add-money-setup": "Add Money Setup" + S,
  "/employer/wallet/add": "Add Money to Wallet" + S,
  "/employer/wallet/transactions": "Transaction History" + S,
  "/employer/wallet/activity": "Wallet Activity" + S,
  "/employer/wallet/withdrawals": "Withdrawal History" + S,
  "/employer/wallet/qr": "My QR Code" + S,
  "/employer/wallet/scan": "Scan & Pay" + S,
  "/employer/wallet/deposit": "Deposit Payment" + S,
  "/employer/wallet": "My Wallet" + S,
  "/employer/requests": "Project Requests" + S,
  "/employer/messages": "Messages" + S,
  "/employer/reviews": "Reviews" + S,
  "/employer/profile/personal": "Personal Information" + S,
  "/employer/profile/professional": "Professional Details" + S,
  "/employer/profile/bank-details": "Bank Details" + S,
  "/employer/profile": "My Profile" + S,
  "/employer/settings/security/mpin": "MPIN Settings" + S,
  "/employer/settings/security/google-authenticator": "Two-Factor Authentication" + S,
  "/employer/settings/security/withdrawal-password": "Withdrawal Password" + S,
  "/employer/settings": "Account Settings" + S,
  "/employer/notification-settings": "Notification Preferences" + S,
  "/employer/notifications": "Notifications" + S,
  "/employer/help-support": "Help & Support" + S,
  "/employer/app": "Get the Mobile App" + S,

  "/client/dashboard": "Client Dashboard" + S,
  "/client/projects/chat": "Project Chat" + S,
  "/client/projects": "My Projects" + S,
  "/client/post-job": "Post a New Job" + S,
  "/client/wallet/add-money-setup": "Add Money Setup" + S,
  "/client/wallet/add": "Add Money to Wallet" + S,
  "/client/wallet/transactions": "Transaction History" + S,
  "/client/wallet/activity": "Wallet Activity" + S,
  "/client/wallet/deposit": "Deposit Payment" + S,
  "/client/wallet": "My Wallet" + S,
  "/client/requests": "Project Requests" + S,
  "/client/messages": "Messages" + S,
  "/client/reviews": "Reviews" + S,
  "/client/profile": "My Profile" + S,
  "/client/settings": "Account Settings" + S,
  "/client/notifications": "Notifications" + S,
  "/client/help-support": "Help & Support" + S,

  "/wallet/deposit": "Deposit Payment" + S,

  "/admin/dashboard": "Admin Dashboard" + S,
  "/admin/users": "User Management" + S,
  "/admin/withdrawals": "Withdrawal Requests" + S,
  "/admin/deposit-requests": "Deposit Requests" + S,
  "/admin/jobs": "Job Management" + S,
  "/admin/projects": "Project Management" + S,
  "/admin/transactions": "Transactions" + S,
  "/admin/wallets": "Wallet Management" + S,
  "/admin/attendance": "Attendance Records" + S,
  "/admin/announcements": "Announcements" + S,
  "/admin/reviews": "Review Management" + S,
  "/admin/support": "Support Tickets" + S,
  "/admin/analytics": "Analytics" + S,
  "/admin/settings": "Admin Settings" + S,
  "/admin/security": "Security Center" + S,
  "/admin/notifications": "Notification Management" + S,
  "/admin/reports": "Reports" + S,
  "/admin/kyc-dashboard": "KYC Dashboard" + S,
  "/admin/subscription-management": "Subscription Management" + S,
  "/admin/commission-management": "Commission Management" + S,
  "/admin/dispute-center": "Dispute Center" + S,
  "/admin/badge-management": "Badge Management" + S,
  "/admin/coin-management": "Coin Management" + S,
  "/admin/gst-tax-reports": "GST & Tax Reports" + S,
  "/admin/promo-management": "Promo Management" + S,
  "/admin/project-analytics": "Project Analytics" + S,
  "/admin/content-moderation": "Content Moderation" + S,
  "/admin/affiliate-management": "Affiliate Management" + S,
  "/admin/fee-configuration": "Fee Configuration" + S,
  "/admin/skill-category-management": "Skill & Category Management" + S,
  "/admin/revenue-analytics": "Revenue Analytics" + S,
  "/admin/milestone-management": "Milestone Management" + S,
  "/admin/invoice-management": "Invoice Management" + S,
  "/admin/review-management": "Review Management" + S,
  "/admin/email-campaigns": "Email Campaigns" + S,
  "/admin/payout-schedule": "Payout Schedule" + S,
  "/admin/mobile-app-management": "Mobile App Management" + S,
  "/admin/waitlist-management": "Waitlist Management" + S,
  "/admin/sla-reports": "SLA Reports" + S,
  "/admin/tds-management": "TDS Management" + S,
  "/admin/talent-showcase": "Talent Showcase" + S,
  "/admin/freelancer-levels": "Freelancer Levels" + S,
  "/admin/chat-monitoring": "Chat Monitoring" + S,
  "/admin/pan-gst-verification": "PAN & GST Verification" + S,
  "/admin/commission-tiers": "Commission Tiers" + S,
  "/admin/bidding-rules": "Bidding Rules" + S,
  "/admin/banner-manager": "Banner Manager" + S,
  "/admin/holiday-calendar": "Holiday Calendar" + S,
  "/admin/rate-cards": "Rate Cards" + S,
  "/admin/activity-log": "Activity Log" + S,
  "/admin/ai-fraud-detection": "AI Fraud Detection" + S,
  "/admin/smart-match-algorithm": "Smart Match Algorithm" + S,
  "/admin/sentiment-analysis": "Sentiment Analysis" + S,
  "/admin/spam-detection": "Spam Detection" + S,
  "/admin/cohort-analysis": "Cohort Analysis" + S,
  "/admin/funnel-analytics": "Funnel Analytics" + S,
  "/admin/revenue-forecasting": "Revenue Forecasting" + S,
  "/admin/geographic-analytics": "Geographic Analytics" + S,
  "/admin/peak-hour-monitor": "Peak Hour Monitor" + S,
  "/admin/partner-reseller": "Partner & Reseller" + S,
  "/admin/b2b-clients": "B2B Clients" + S,
  "/admin/affiliate-payouts": "Affiliate Payouts" + S,
  "/admin/referral-leaderboard": "Referral Leaderboard" + S,
  "/admin/marketplace-trends": "Marketplace Trends" + S,
  "/admin/contract-templates": "Contract Templates" + S,
  "/admin/nda-management": "NDA Management" + S,
  "/admin/gdpr-compliance": "GDPR Compliance" + S,
  "/admin/grievance-redressal": "Grievance Redressal" + S,
  "/admin/court-orders": "Court Orders" + S,
  "/admin/skill-assessment": "Skill Assessment" + S,
  "/admin/portfolio-review": "Portfolio Review" + S,
  "/admin/time-tracking": "Time Tracking" + S,
  "/admin/project-templates": "Project Templates" + S,
  "/admin/testimonial-approval": "Testimonial Approval" + S,
  "/admin/push-notification-campaigns": "Push Notification Campaigns" + S,
  "/admin/sms-campaign-manager": "SMS Campaign Manager" + S,
  "/admin/email-campaign-manager": "Email Campaign Manager" + S,
  "/admin/abandoned-user-reengagement": "Abandoned User Re-engagement" + S,
  "/admin/ab-test-manager": "A/B Test Manager" + S,
  "/admin/badge-achievement-manager": "Badge & Achievement Manager" + S,
  "/admin/leaderboard-manager": "Leaderboard Manager" + S,
  "/admin/loyalty-points-system": "Loyalty Points System" + S,
  "/admin/level-tier-upgrade-rules": "Level & Tier Upgrade Rules" + S,
  "/admin/app-version-manager": "App Version Manager" + S,
  "/admin/pwa-analytics": "PWA Analytics" + S,
  "/admin/deep-link-manager": "Deep Link Manager" + S,
  "/admin/app-store-review-monitor": "App Store Review Monitor" + S,
  "/admin/live-chat-monitor": "Live Chat Monitor" + S,
  "/admin/ticket-escalation-matrix": "Ticket Escalation Matrix" + S,
  "/admin/sla-breach-alerts": "SLA Breach Alerts" + S,
  "/admin/user-onboarding-funnel": "User Onboarding Funnel" + S,
  "/admin/third-party-api-key-manager": "Third-Party API Key Manager" + S,
  "/admin/dns-domain": "DNS & Domain Management" + S,
  "/admin/duplicate-accounts": "Duplicate Accounts" + S,
  "/admin/email-deliverability": "Email Deliverability" + S,
  "/admin/encryption-keys": "Encryption Keys" + S,
  "/admin/export-format": "Export Format" + S,
  "/admin/external-api-monitor": "External API Monitor" + S,
  "/admin/external-failover": "External Service Failover" + S,
  "/admin/feature-dependency": "Feature Dependency" + S,
  "/admin/feature-flags": "Feature Flags" + S,
  "/admin/feature-conflicts": "Feature Toggle Conflicts" + S,
  "/admin/file-paths": "File Path Management" + S,
  "/admin/file-permissions": "File Permissions" + S,
  "/admin/file-upload-validation": "File Upload Validation" + S,
  "/admin/gateway-failover": "Gateway Failover" + S,
  "/admin/job-scheduler": "Job Scheduler" + S,
  "/admin/localization": "Localization" + S,
  "/admin/maintenance-mode": "Maintenance Mode" + S,
  "/admin/module-dependency": "Module Dependency" + S,
  "/admin/multi-admin-conflict": "Multi-Admin Conflict" + S,
  "/admin/notification-control": "Notification Control" + S,
  "/admin/pagination-validator": "Pagination Validator" + S,
  "/admin/performance-monitor": "Performance Monitor" + S,
  "/admin/query-validation": "Query Validation" + S,
  "/admin/queue-management": "Queue Management" + S,
  "/admin/rate-limit-config": "Rate Limit Config" + S,
  "/admin/rbac-security": "RBAC Security" + S,
  "/admin/report-validation": "Report Validation" + S,
  "/admin/restore-version": "Restore Version Control" + S,
  "/admin/role-escalation": "Role Escalation" + S,
  "/admin/search-index": "Search Index" + S,
  "/admin/secure-audit-log": "Secure Audit Log" + S,
  "/admin/secure-session-mgr": "Secure Session Manager" + S,
  "/admin/session-expiry": "Session Expiry" + S,
  "/admin/session-storage": "Session Storage" + S,
  "/admin/session-sync": "Session Sync" + S,
  "/admin/smart-alerts": "Smart Alert Manager" + S,
  "/admin/soft-delete-cleanup": "Soft Delete Cleanup" + S,
  "/admin/ssl-monitor": "SSL Monitor" + S,
  "/admin/storage-manager": "Storage Manager" + S,
  "/admin/time-slots": "Time Slot Management" + S,
  "/admin/timezone-manager": "Timezone Manager" + S,
  "/admin/traffic-management": "Traffic Management" + S,
  "/admin/webhook-monitor": "Webhook Monitor" + S,
  "/admin/xss-protection": "XSS Protection" + S,
};

const DESCRIPTIONS: Record<string, string> = {
  "/": "Find top freelancers in India for web development, design, content writing & digital marketing. Post projects free, get instant bids. Join Freelan Space today!",
  "/landing": "Explore India's fastest-growing freelance marketplace. Connect with skilled professionals for every project. Sign up free and start hiring or earning today.",
  "/login": "Log in to your Freelan Space account to manage projects, track earnings, and connect with clients or freelancers across India. Secure and quick access.",
  "/forgot-password": "Forgot your Freelan Space password? Reset it quickly using your registered email. Get back to freelancing and hiring in just a few easy steps.",
  "/reset-password": "Reset your Freelan Space account password securely. Enter your new password to regain full access to your dashboard, wallet, and active projects.",
  "/register/employee": "Create your free freelancer account on Freelan Space. Showcase your skills, bid on projects, and start earning from clients across India today.",
  "/register/freelancer": "Create your free freelancer account on Freelan Space. Showcase your skills, bid on projects, and start earning from clients across India today.",
  "/register/employer": "Sign up as an employer on Freelan Space. Post jobs, review proposals from skilled freelancers, and hire the best talent in India within minutes.",
  "/register/client": "Sign up as a client on Freelan Space. Post jobs, review proposals from skilled freelancers, and hire the best talent in India within minutes.",
  "/verification-pending": "Your Freelan Space account is under review. Check your email for the verification link or contact support for help completing your registration.",
  "/install": "Install the Freelan Space app on your device for seamless project management, instant notifications, and easy access to your wallet on the go.",
  "/complete-profile": "Complete your Freelan Space profile to unlock all features. Add your skills, portfolio, and bank details to start bidding and earning right away.",
  "/categories": "Explore all freelance service categories on Freelan Space — web development, graphic design, content writing, SEO, video editing, and many more skills.",
  "/projects": "Browse hundreds of live freelance projects in India. Filter by category, budget, and skill. Find your perfect project and submit a winning proposal today.",
  "/pricing": "View Freelan Space pricing plans for freelancers and employers. Choose the plan that fits your needs with zero commission for the first three months.",
  "/how-it-works": "Learn how Freelan Space connects freelancers with employers. Post jobs, bid on projects, collaborate safely, and get paid securely — all in one platform.",
  "/community": "Join the Freelan Space freelancer community. Share experiences, get advice, discuss projects, and network with thousands of professionals across India.",
  "/about": "Learn about Freelan Space — India's trusted freelance marketplace. Our mission is to empower skilled professionals and businesses to grow together seamlessly.",
  "/blog": "Read the Freelan Space blog for freelancing tips, success stories, platform updates, and industry insights to help you grow your career and business in India.",
  "/careers": "Join the Freelan Space team! Explore exciting career opportunities in product, engineering, marketing, and support. Help us build India's best freelance platform.",
  "/contact": "Get in touch with the Freelan Space support team. We're here to help with account issues, billing queries, and platform-related questions for all users.",
  "/unsubscribe": "Unsubscribe from Freelan Space email notifications. Manage your communication preferences to control the updates and alerts you receive from us.",
  "/legal": "Review Freelan Space legal documents including Terms of Service, Privacy Policy, and Refund Policy. Understand your rights and responsibilities on the platform.",

  "/employee/dashboard": "Welcome to your Freelan Space freelancer dashboard. View active projects, pending bids, earnings summary, and quick actions all in one place.",
  "/employee/attendance": "Track your daily attendance and work hours on Freelan Space. Mark check-in and check-out times and maintain a reliable record for your clients.",
  "/employee/projects": "Browse and bid on available freelance projects on Freelan Space. Filter by category, budget, and skills to find the best matching opportunities for you.",
  "/employee/requests": "View all your submitted project proposals on Freelan Space. Track proposal status, follow up with clients, and manage your active bids efficiently.",
  "/employee/bids": "Manage all your project bids on Freelan Space. View bid status, use proposal templates, and track responses from employers across all active bids.",
  "/employee/earnings": "View your total freelance earnings on Freelan Space. Analyse monthly income trends, download invoices, and track all completed project payments.",
  "/employee/reviews": "Read feedback and ratings from your clients on Freelan Space. Monitor your reputation, respond to reviews, and build trust with future employers.",
  "/employee/badges": "Earn verified skill badges on Freelan Space by passing skill assessments. Showcase your expertise and stand out from other freelancers to win more bids.",
  "/employee/portfolio": "Manage and showcase your freelance portfolio on Freelan Space. Add projects, images, and descriptions to impress clients and win high-value bids.",
  "/employee/wallet": "Manage your Freelan Space wallet. Check balance, add money, withdraw earnings, view transactions, and transfer funds securely within the platform.",
  "/employee/wallet/add": "Add money to your Freelan Space wallet easily. Use UPI, net banking, or cards to top up your balance and participate in premium project bidding.",
  "/employee/wallet/transactions": "View your complete transaction history on Freelan Space. Track all credits, debits, withdrawals, and transfers with detailed date and amount records.",
  "/employee/wallet/withdraw": "Withdraw your freelance earnings from Freelan Space to your bank account. Submit a withdrawal request and receive funds securely within 24 hours.",
  "/employee/wallet/scan": "Scan a QR code to send or receive payments instantly on Freelan Space. Quickly transfer wallet funds to any registered user in seconds.",
  "/employee/profile": "Update and manage your Freelan Space freelancer profile. Keep your personal details, skills, and professional information accurate to attract better clients.",
  "/employee/profile/personal": "Update your personal information on Freelan Space including name, date of birth, address, and contact details to keep your account profile up to date.",
  "/employee/profile/professional": "Add and update your professional details on Freelan Space. List your skills, experience, education, and specialisations to attract the right clients.",
  "/employee/profile/bank-details": "Add or update your bank account details on Freelan Space for seamless withdrawal of your freelance earnings directly to your bank account.",
  "/employee/profile/aadhaar-verification": "Complete Aadhaar-based KYC verification on Freelan Space to unlock higher withdrawal limits and build trust with potential clients and employers.",
  "/employee/settings": "Manage your Freelan Space account settings. Update security preferences, notification settings, privacy options, and connected app configurations.",
  "/employee/notifications": "View all your Freelan Space notifications. Stay updated on project bids, client messages, payment alerts, and important platform announcements.",
  "/employee/help-support": "Get help from the Freelan Space support team. Browse FAQs, raise a support ticket, or chat with our team for quick resolution of your queries.",

  "/freelancer/dashboard": "Welcome to your Freelan Space freelancer dashboard. View active projects, pending bids, earnings summary, and quick actions all in one place.",
  "/freelancer/projects": "Browse and bid on available freelance projects on Freelan Space. Filter by category, budget, and skills to find the best matching opportunities.",
  "/freelancer/earnings": "View your total freelance earnings on Freelan Space. Analyse monthly income trends, download invoices, and track all completed project payments.",
  "/freelancer/wallet": "Manage your Freelan Space wallet. Check balance, add money, withdraw earnings, view transactions, and transfer funds securely within the platform.",
  "/freelancer/profile": "Update and manage your Freelan Space freelancer profile. Keep your personal details, skills, and professional information accurate to attract better clients.",
  "/freelancer/settings": "Manage your Freelan Space account settings. Update security preferences, notification settings, privacy options, and connected app configurations.",
  "/freelancer/help-support": "Get help from the Freelan Space support team. Browse FAQs, raise a support ticket, or chat with our team for quick resolution of your queries.",

  "/employer/dashboard": "Manage all your freelance projects from the Freelan Space employer dashboard. Review bids, track progress, release payments, and hire top talent.",
  "/employer/projects": "View and manage all your posted projects on Freelan Space. Track milestones, communicate with freelancers, and complete projects on time and budget.",
  "/employer/post-job": "Post a new freelance job on Freelan Space. Describe your requirements, set your budget, and receive proposals from skilled Indian freelancers quickly.",
  "/employer/wallet": "Manage your Freelan Space employer wallet. Add funds, track project payments, view transaction history, and release milestone payments to freelancers.",
  "/employer/requests": "Review all incoming freelancer proposals for your posted jobs on Freelan Space. Compare bids, check profiles, and hire the most suitable candidate.",
  "/employer/profile": "Update your Freelan Space employer profile. Keep business details, contact information, and professional credentials accurate for freelancer trust.",
  "/employer/settings": "Manage your Freelan Space employer account settings. Configure notifications, security options, and billing preferences for your hiring account.",
  "/employer/help-support": "Get help from the Freelan Space support team. Browse FAQs, raise a support ticket, or chat with our team for quick resolution of your hiring queries.",

  "/client/dashboard": "Manage all your freelance projects from the Freelan Space client dashboard. Review bids, track progress, release payments, and hire top talent in India.",
  "/client/projects": "View and manage all your posted projects on Freelan Space. Track milestones, communicate with freelancers, and complete projects on time and budget.",
  "/client/post-job": "Post a new freelance job on Freelan Space. Describe your requirements, set your budget, and receive proposals from skilled Indian freelancers quickly.",
  "/client/wallet": "Manage your Freelan Space client wallet. Add funds, track project payments, view transaction history, and release milestone payments to freelancers.",
  "/client/requests": "Review all incoming freelancer proposals for your posted jobs on Freelan Space. Compare bids, check profiles, and hire the most suitable candidate.",
  "/client/help-support": "Get help from the Freelan Space support team. Browse FAQs, raise a support ticket, or chat with our team for quick resolution of your queries.",

  "/admin/dashboard": "Freelan Space admin dashboard. Monitor platform activity, review key metrics, manage users, and oversee all operations from a single control panel.",
  "/admin/users": "Manage all registered users on Freelan Space. View profiles, handle verifications, suspend accounts, and maintain user quality across the platform.",
  "/admin/withdrawals": "Review and process freelancer withdrawal requests on Freelan Space. Approve, reject, or hold payouts and ensure secure fund disbursement to users.",
  "/admin/deposit-requests": "Manage and verify all wallet deposit requests on Freelan Space. Review payment proof, approve credits, and maintain clean financial records.",
  "/admin/jobs": "Manage all jobs posted on the Freelan Space platform. Review, approve, moderate, and remove job listings to maintain quality and compliance standards.",
  "/admin/transactions": "View complete transaction logs across the Freelan Space platform. Monitor wallet credits, debits, transfers, and payments for audit and compliance.",
  "/admin/analytics": "Access platform-wide analytics on Freelan Space. Monitor user growth, project trends, revenue metrics, and engagement data to drive informed decisions.",
  "/admin/settings": "Configure global platform settings for Freelan Space. Manage fees, limits, feature toggles, and system configurations from the admin control panel.",
  "/admin/kyc-dashboard": "Manage KYC verification requests on Freelan Space. Review Aadhaar, PAN, and bank verification submissions and approve or reject pending requests.",
  "/admin/support": "Handle all user support tickets on Freelan Space. Respond to queries, escalate issues, and resolve platform-related problems quickly and efficiently.",
  "/admin/security": "Monitor and manage platform security on Freelan Space. Review suspicious activity, manage blocked IPs, and configure security rules for all users.",
};

const KEYWORDS: Record<string, string> = {
  "/": "freelance jobs india, hire freelancers, freelance platform india, online freelancing, work from home jobs india, freelancer marketplace, find freelancers online, post freelance project",
  "/landing": "freelance services india, hire skilled freelancers, online work platform, best freelance site india, freelance marketplace india",
  "/login": "freelancer login, employer login, freelance account login, freelan space login",
  "/forgot-password": "reset freelance account password, forgot password freelan space",
  "/reset-password": "reset password freelan space, account recovery freelancer",
  "/register/employee": "register as freelancer india, create freelancer account, freelance signup india, join freelance platform",
  "/register/freelancer": "register as freelancer india, create freelancer account, freelance signup india, join freelance platform",
  "/register/employer": "hire freelancers india, post jobs online, employer registration freelance, find talent india",
  "/register/client": "hire freelancers india, post jobs online, client registration freelance, find talent india",
  "/verification-pending": "account verification freelancer, verify email freelan space",
  "/install": "install freelan space app, freelance app india, pwa freelancer app, download freelance app",
  "/complete-profile": "complete freelancer profile, setup freelance account, add portfolio skills",
  "/categories": "freelance categories india, web development freelance, graphic design freelance, content writing jobs, seo freelancer, video editing jobs, data entry freelance, digital marketing freelancer",
  "/projects": "freelance projects india, find freelance work, online project work, bid on projects india, remote work opportunities, freelance assignments india",
  "/pricing": "freelance platform pricing india, hire freelancers cost, freelance subscription plans, freelan space plans, affordable freelancing platform",
  "/how-it-works": "how freelancing works india, hire freelancer online, freelance marketplace guide, post project and hire, freelance bidding process",
  "/community": "freelancer community india, freelancing forum india, freelance network india, connect with freelancers, freelancing tips community",
  "/about": "about freelan space, freelance marketplace india, online work platform india, trusted freelance site india, freelancer employer connect",
  "/blog": "freelancing tips india, freelance career advice, work from home tips, freelancing success stories, online earning tips india",
  "/careers": "freelan space careers, jobs at freelance startup india, tech jobs india, work at freelance company",
  "/contact": "contact freelan space, freelance platform support, customer care freelancer india, help freelan space",
  "/legal": "freelan space terms of service, privacy policy freelancer, refund policy freelance platform, user agreement",
  "/unsubscribe": "unsubscribe emails freelan space, manage email preferences",

  "/employee/dashboard": "freelancer dashboard india, manage freelance projects, track earnings freelancer, freelance work summary",
  "/employee/projects": "find freelance projects, bid on projects india, freelance work opportunities, browse freelance jobs",
  "/employee/requests": "my freelance proposals, track bids india, submitted proposals freelancer, proposal status",
  "/employee/bids": "freelance bids india, manage bids freelancer, proposal templates freelance, bid tracking",
  "/employee/earnings": "freelancer earnings india, freelance income tracker, invoice generator freelancer, payment history freelancer",
  "/employee/reviews": "freelancer client reviews, freelance ratings india, client feedback freelancer, reputation management",
  "/employee/badges": "skill badges freelancer india, verified freelancer badge, skill assessment india, freelance certification",
  "/employee/portfolio": "freelancer portfolio india, showcase freelance work, portfolio management, freelance profile portfolio",
  "/employee/wallet": "freelancer wallet india, withdraw earnings upi, freelance payment wallet, wallet balance freelancer",
  "/employee/wallet/add": "add money freelancer wallet, top up wallet india, upi wallet freelancer",
  "/employee/wallet/transactions": "freelancer transaction history, wallet transactions india, payment records freelancer",
  "/employee/wallet/withdraw": "withdraw freelance earnings, bank transfer freelancer india, withdrawal request",
  "/employee/wallet/scan": "scan qr pay freelancer, qr code payment freelance, wallet transfer india",
  "/employee/profile": "freelancer profile india, update freelancer profile, manage freelance account",
  "/employee/profile/personal": "personal info freelancer, update contact details, freelancer account details",
  "/employee/profile/professional": "professional profile freelancer, skills and experience, freelancer expertise india",
  "/employee/profile/bank-details": "bank details freelancer india, withdrawal bank account, add bank account freelancer",
  "/employee/profile/aadhaar-verification": "aadhaar kyc freelancer india, identity verification freelance, kyc verification india",
  "/employee/settings": "freelancer account settings, security settings freelancer, notification preferences",
  "/employee/notifications": "freelancer notifications, project alerts, payment notifications freelancer",
  "/employee/help-support": "freelancer help india, freelance support ticket, faq freelancer platform",
  "/employee/attendance": "freelancer attendance tracker, work hours tracker india, daily attendance freelancer",
  "/employee/get-free": "free coins freelancer, earn free rewards freelancer, referral coins freelance",
  "/employee/get-coins": "earn coins freelancer, buy coins freelance platform, coins freelan space",

  "/freelancer/dashboard": "freelancer dashboard india, manage freelance projects, track earnings freelancer",
  "/freelancer/projects": "find freelance projects, bid on projects india, freelance work opportunities",
  "/freelancer/bids": "freelance bids india, manage bids freelancer, bid tracking platform",
  "/freelancer/earnings": "freelancer earnings india, freelance income tracker, invoice generator",
  "/freelancer/reviews": "freelancer client reviews, client feedback, freelance ratings india",
  "/freelancer/badges": "skill badges freelancer india, verified freelancer, skill certification",
  "/freelancer/portfolio": "freelancer portfolio india, showcase work, portfolio management",
  "/freelancer/wallet": "freelancer wallet india, withdraw earnings, upi payment freelance",
  "/freelancer/profile": "freelancer profile india, update freelancer details, manage freelance account",
  "/freelancer/settings": "freelancer account settings, security settings, notification preferences",
  "/freelancer/help-support": "freelancer help india, support ticket, faq freelancer",
  "/freelancer/attendance": "freelancer attendance tracker, work hours india",

  "/employer/dashboard": "employer dashboard india, manage freelancers, project management hire, track freelance projects",
  "/employer/projects": "manage freelance projects india, track milestones, project status employer",
  "/employer/post-job": "post freelance job india, hire freelancer online, job posting freelance, find talent india",
  "/employer/requests": "review freelancer proposals, compare bids, hire freelancer india",
  "/employer/wallet": "employer wallet india, pay freelancers, project payment wallet",
  "/employer/profile": "employer profile freelance, business profile india, hiring company profile",
  "/employer/settings": "employer account settings, billing preferences, notification settings",
  "/employer/help-support": "employer help india, support freelance platform, hiring assistance",

  "/client/dashboard": "client dashboard india, manage freelancers, project management, hire talent",
  "/client/projects": "manage client projects india, track milestones, freelance project status",
  "/client/post-job": "post job india, hire freelancer, project posting freelance",
  "/client/wallet": "client wallet india, pay freelancers, project payment",
  "/client/requests": "review proposals, compare freelancer bids, hire india",
  "/client/help-support": "client support india, freelance platform help",
};

const DEFAULT_KEYWORDS = "freelance jobs india, hire freelancers, freelance platform india, online freelancing india, work from home jobs, freelancer marketplace, post projects, find freelancers";
const DEFAULT_TITLE = "Freelance Jobs in India — Hire Top Freelancers | Freelan Space";
const DEFAULT_DESC = "Freelan Space — India's trusted freelance marketplace. Connect skilled freelancers with clients for web, design, content & more. Post projects free and hire today.";

function getTitle(pathname: string): string {
  if (TITLES[pathname]) return TITLES[pathname];
  const sorted = Object.keys(TITLES).sort((a, b) => b.length - a.length);
  for (const key of sorted) {
    if (pathname.startsWith(key + "/") || pathname === key) return TITLES[key];
  }
  return DEFAULT_TITLE;
}

function getDescription(pathname: string): string {
  if (DESCRIPTIONS[pathname]) return DESCRIPTIONS[pathname];
  const sorted = Object.keys(DESCRIPTIONS).sort((a, b) => b.length - a.length);
  for (const key of sorted) {
    if (pathname.startsWith(key + "/") || pathname === key) return DESCRIPTIONS[key];
  }
  return DEFAULT_DESC;
}

function getKeywords(pathname: string): string {
  if (KEYWORDS[pathname]) return KEYWORDS[pathname];
  const sorted = Object.keys(KEYWORDS).sort((a, b) => b.length - a.length);
  for (const key of sorted) {
    if (pathname.startsWith(key + "/") || pathname === key) return KEYWORDS[key];
  }
  return DEFAULT_KEYWORDS;
}

function setMetaTag(name: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("name", name);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

export default function PageTitleManager() {
  const { pathname } = useLocation();

  useEffect(() => {
    document.title = getTitle(pathname);
    setMetaTag("description", getDescription(pathname));
    setMetaTag("keywords", getKeywords(pathname));
  }, [pathname]);

  return null;
}
